name: Build And Deploy Apps

on:
  push:
    branches: [ "master" ]
    paths:
      - apps/bitcoin-fetcher/**
      - apps/empty-responder/**
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      reason: 
        description: 'Reason'
        required: true
        default: 'Manual trigger'
jobs:
  build-and-deploy-bitcoin-fetcher:
    env:
      appName: bitcoin-fetcher
      dockerHubRepo: "${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-fetcher"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/${{ env.appName }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image    
      run: docker build . --tag $dockerHubRepo:latest
    - name: Push the Docker image
      run: docker push $dockerHubRepo:latest

  build-and-deploy-empty-responder:
    env:
      appName: empty-responder
      dockerHubRepo: "${{ secrets.DOCKERHUB_USERNAME }}/empty-responder"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/${{ env.appName }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image    
      run: docker build . --tag $dockerHubRepo:latest
    - name: Push the Docker image
      run: docker push $dockerHubRepo:latest
