on: 
  workflow_dispatch:
    inputs:
      cluster-name: 
        description: 'cluster name. Used for dns-prefix and resource-group name'
        required: true
        default: 'btc-assignment'

env:
  KUBECONFIG_PATH: ${GITHUB_WORKSPACE}/kubernetes/kubeconfig.northeurope.json
  NO_PATH: ${GITHUB_WORKSPACE}/kubernetes/kubeconfigfddd.zz


name: create-secret-test
jobs:
  create-secret-test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Kubeconfig as env var
      run: |
        chmod 400 ${{ env.KUBECONFIG_PATH }}
        kube_config=$(cat ${{ env.KUBECONFIG_PATH }} | base64 -w 0)
        echo "::add-mask::$kube_config"
        echo "KUBE_CONFIG=$kube_config" >> $GITHUB_ENV

    - name: Upload Kubeconfig
      uses: gliech/create-github-secret-action@v1
      with:
        name: KUBE_CONFIG
        value: ${{ env.KUBE_CONFIG }}
        pa_token: ${{ secrets.GH_TOKEN }}

