on: 
  workflow_dispatch:
    inputs:
      resource-group: 
        description: 'Resource Group Name To Delete'
        required: true
        default: 'btc-assignment'

name: delete-cluster
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    # - name: Azure CLI script file
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.42.0
    #     inlineScript: |
    #       chmod +x $GITHUB_WORKSPACE/sampleScript.sh
    #       $GITHUB_WORKSPACE/sampleScript.sh
    - name: Delete Cluster
      uses: azure/CLI@v1
      with:
        azcliversion: 2.42.0
        inlineScript: |
          az group delete --name ${{ github.event.inputs.resource-group }} --yes
