
on: 
  workflow_dispatch:
    inputs:
      resason: 
        description: 'reason'
        default: 'btc-assignment'
  workflow_call:
    inputs:
      resason: 
        description: 'reason'
        type: string
        default: 'btc-assignment'

name: helm install nginx-ingress
jobs:
  deploy-nginx-ingress:
    env:
      KUBECONFIG: ./kubeconfig
    runs-on: ubuntu-latest
    steps:

    - uses: azure/setup-helm@v3
      with:
        version: 'v3.10.1'
      id: install

    - name: get kubeconfig
      run: |
        mkdir -p ~/.kube
        echo -n ${{ secrets.KUBE_CONFIG }} | base64 -d > ./kubeconfig
        stat ./kubeconfig
        echo "1st try"
        echo "KUBECONFIG: $KUBECONFIG"
        kubectl config view
        echo "kubeconfig looks like 1st try:"
        cat ./kubeconfig

    - name: wait for kubernetes api to be ready
      run: |
        echo "Waiting for kubernetes api to be ready2"
        cat ./kubeconfig
        kubectl config view
        echo "kubeconfig looks like:"
        while ! kubectl get node
        do
            echo "Waiting for kubernetes api to be ready3"
            kubectl config view
            echo "kubeconfig looks like:"
            cat ./kubeconfig
            sleep 10
        done

    - name: wait for all nodes to be ready
      run: |
        kubectl wait --for=condition=Ready node --all --timeout=900s

    - name: install nginx-ingress
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install --create-namespace -n nginx-ingress nginx-ingress ingress-nginx/ingress-nginx
    - name: get pods
      run: |
        kubectl get pods -n nginx-ingress

