name: Build empty-responder

on:
  push:
    branches: [ "master" ]
    paths:
      - apps/empty-responder/**
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      reason: 
        description: 'Reason'
        required: true
        default: 'Manual trigger'
env:
  dockerHubRepo: navelevi/empty-responder
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/empty-responder
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image    
      run: docker build . --tag $dockerHubRepo:latest
    - name: Push the Docker image
      run: docker push $dockerHubRepo:latest
