
on: 
  workflow_dispatch:
    inputs:
      resason: 
        description: 'reason'
        required: true
        default: 'btc-assignment'

name: helm install nginx-ingress
jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - uses: azure/setup-helm@v3
      with:
        version: 'v3.10.1'
      id: install

    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.2'
      id: install

    - name: get kubeconfig
      run: |
        mkdir -p ~/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 -d > $HOME/.kube/config
        stat $HOME/.kube/config
        kubectl get ns
    # - name: create namespace
    #   run: |
    #     kubectl create namespace nginx-ingress
    - name: install nginx-ingress
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install nginx-ingress ingress-nginx/ingress-nginx
        kubectl get pods -n ingress-nginx