
on: 
  workflow_dispatch:
  workflow_run:
    workflows: [create-cluster]
    types:
      - completed

name: deploy-nginx-ingress
jobs:
  deploy-ingress-nginx:
    timeout-minutes: 30
    env:
      KUBECONFIG: ./kubeconfig
    runs-on: ubuntu-latest
    steps:

    - uses: azure/setup-helm@v3
      with:
        version: 'v3.10.1'
      id: install

    - name: get kubeconfig
      run: |
        mkdir -p ~/.kube
        echo -n ${{ secrets.KUBE_CONFIG }} | base64 -d > ./kubeconfig

    - name: wait for kubernetes api to be ready
      run: |
        echo "Waiting for kubernetes api to be ready2"
        while ! kubectl get node
        do
            echo "Waiting for kubernetes api to be ready3"
            sleep 10
        done

    - name: wait for all pods to be ready
      run: |
        kubectl wait --for=condition=Ready pod --all -A --timeout=900s

    - name: install ingress-nginx
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install --create-namespace -n ingress-nginx ingress-nginx ingress-nginx/ingress-nginx --atomic --timeout 600s 
        until [ "$(helm upgrade --install --create-namespace -n ingress-nginx ingress-nginx ingress-nginx/ingress-nginx --atomic --timeout 600s)" ]; do
            echo "Helm install failed. Waiting 60 seoncds for kubernetes"
            sleep 60
        done
        echo "ingress-nginx installed"

    - name: Print ingress-nginx LB IP
      run: |
        until [ -n "$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" ]; do
            echo "Waiting for LoadBalancer IP"
            sleep 10
        done
        echo "External IP is: $(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
