on: 
  workflow_dispatch:
    inputs:
      test: 
        description: 'testing'
        required: true
        default: 'btc-assignment'

name: create-secret-test
jobs:
  create-secret-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: pwd
      run: pwd
    - name: ls
      run: ls -lah

    - name: set-variable
      run: |
        kubeconfig=$(cat kubernetes/kubeconfig.northeurope.json | base64 -w 0)
        echo "::add-mask::$kubeconfig"
        echo "KUBECONFIG=$kubeconfig" >> $GITHUB_ENV

    - uses: gliech/create-github-secret-action@v1
      with:
        name: KUBECONFIG
        value: ${{ env.KUBECONFIG }}
        pa_token: ${{ secrets.GH_TOKEN }}
