on: 
  workflow_dispatch:
    inputs:
      test: 
        description: 'testing'
        required: true
        default: 'btc-assignment'

name: create-secret-test
jobs:
  create-secret-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: pwd
      run: pwd
    - name: ls
      run: ls -lah
    - name: set-variable
      run: |
        kubeconfig=$(cat kubernetes/testFile.yaml | base64)
        echo $kubeconfig
        echo "KUBECONFIG=$kubeconfig" >> $GITHUB_ENV


      # echo "::set-env name=KUBECONFIG2::$kubeconfig"